# Databricks notebook source
# MAGIC %sql
# MAGIC select
# MAGIC   base.*,
# MAGIC   ci.`Average Income` as fsa_income,
# MAGIC   case 
# MAGIC     when income > 0 and fsa_income > 0 then income - ci.`Average Income`
# MAGIC     else -1000000
# MAGIC   end as income_gap
# MAGIC from
# MAGIC   (select
# MAGIC     brand,
# MAGIC     last_day(createdAt) as month_end,
# MAGIC     a.userId,
# MAGIC     -- origin,
# MAGIC     AM02,
# MAGIC     AM04,
# MAGIC     AM07,
# MAGIC     AM167,
# MAGIC     AM21,
# MAGIC     AM216,
# MAGIC     AM29,
# MAGIC     AM33,
# MAGIC     AM34,
# MAGIC     AM36,
# MAGIC     AM41,
# MAGIC     AM42,
# MAGIC     AM43,
# MAGIC     AM44,
# MAGIC     AM57,
# MAGIC     AM60,
# MAGIC     AM84,
# MAGIC     AM91,
# MAGIC     AT01,
# MAGIC     AT02,
# MAGIC     AT07,
# MAGIC     AT21,
# MAGIC     AT29,
# MAGIC     AT33,
# MAGIC     AT34,
# MAGIC     AT36,
# MAGIC     AT60,
# MAGIC     AT84,
# MAGIC     BC02,
# MAGIC     BC04,
# MAGIC     BC141,
# MAGIC     BC142,
# MAGIC     BC143,
# MAGIC     BC144,
# MAGIC     BC145,
# MAGIC     BC147,
# MAGIC     BC148,
# MAGIC     BC21,
# MAGIC     BC33,
# MAGIC     BC34,
# MAGIC     BC36,
# MAGIC     BC60,
# MAGIC     BC62,
# MAGIC     BC75,
# MAGIC     BC76,
# MAGIC     BC77,
# MAGIC     BC78,
# MAGIC     BC79,
# MAGIC     BC80,
# MAGIC     BC84,
# MAGIC     BC85,
# MAGIC     BC86,
# MAGIC     BC91,
# MAGIC     BC94,
# MAGIC     BR02,
# MAGIC     BR04,
# MAGIC     BR60,
# MAGIC     BR62,
# MAGIC     BR84,
# MAGIC     BR91,
# MAGIC     GO06,
# MAGIC     GO07,
# MAGIC     GO11,
# MAGIC     GO14,
# MAGIC     GO141,
# MAGIC     GO148,
# MAGIC     GO149,
# MAGIC     GO15,
# MAGIC     GO151,
# MAGIC     GO152,
# MAGIC     GO17,
# MAGIC     GO21,
# MAGIC     GO26,
# MAGIC     GO80,
# MAGIC     GO81,
# MAGIC     GO83,
# MAGIC     GO91,
# MAGIC     -- IDXBE01,
# MAGIC     -- IDXBE02,
# MAGIC     -- IDXBE03,
# MAGIC     -- IDXBE04,
# MAGIC     -- IDXBE05,
# MAGIC     -- IDXBE06,
# MAGIC     -- IDXBE07,
# MAGIC     -- IDXBE08,
# MAGIC     -- IDXBE09,
# MAGIC     -- IDXBE10,
# MAGIC     -- IDXBE11,
# MAGIC     -- IDXBE12,
# MAGIC     -- IDXBE13,
# MAGIC     -- IDXBE14,
# MAGIC     -- IDXBE15,
# MAGIC     -- IDXBE16,
# MAGIC     -- IDXBE17,
# MAGIC     -- IDXBE18,
# MAGIC     -- IDXBE19,
# MAGIC     -- IDXBE21,
# MAGIC     -- IDXBE22,
# MAGIC     -- IDXBE23,
# MAGIC     -- IDXBE24,
# MAGIC     -- IDXBE26,
# MAGIC     -- IDXBE27,
# MAGIC     -- IDXBE28,
# MAGIC     -- IDXBE30,
# MAGIC     -- IDXBE31,
# MAGIC     -- IDXBE35,
# MAGIC     -- IDXBE36,
# MAGIC     -- IDXBE38,
# MAGIC     -- IDXBE39,
# MAGIC     -- IDXBE40,
# MAGIC     -- IDXBE42,
# MAGIC     -- IDXBE43,
# MAGIC     -- IDXBE44,
# MAGIC     -- IDXBE45,
# MAGIC     -- IDXBE46,
# MAGIC     -- IDXBE47,
# MAGIC     -- IDXBE48,
# MAGIC     -- IDXBE49,
# MAGIC     -- IDXBE50,
# MAGIC     -- IDXBE51,
# MAGIC     -- IDXBE52,
# MAGIC     -- IDXBE53,
# MAGIC     -- IDXCF191,
# MAGIC     -- IDXCF193,
# MAGIC     -- IDXCF194,
# MAGIC     -- IDXCF237,
# MAGIC     -- IDXCF239,
# MAGIC     -- IDXFR01,
# MAGIC     -- IDXFR02,
# MAGIC     -- IDXFR03,
# MAGIC     -- IDXFR04,
# MAGIC     -- IDXFR05,
# MAGIC     -- IDXFR06,
# MAGIC     -- IDXFR07,
# MAGIC     -- IDXFR08,
# MAGIC     -- IDXFR09,
# MAGIC     -- IDXFR10,
# MAGIC     -- IDXFR100,
# MAGIC     -- IDXFR101,
# MAGIC     -- IDXFR102,
# MAGIC     -- IDXFR103,
# MAGIC     -- IDXFR104,
# MAGIC     -- IDXFR105,
# MAGIC     -- IDXFR106,
# MAGIC     -- IDXFR107,
# MAGIC     -- IDXFR108,
# MAGIC     -- IDXFR109,
# MAGIC     -- IDXFR11,
# MAGIC     -- IDXFR110,
# MAGIC     -- IDXFR111,
# MAGIC     -- IDXFR112,
# MAGIC     -- IDXFR113,
# MAGIC     -- IDXFR114,
# MAGIC     -- IDXFR115,
# MAGIC     -- IDXFR116,
# MAGIC     -- IDXFR117,
# MAGIC     -- IDXFR118,
# MAGIC     -- IDXFR12,
# MAGIC     -- IDXFR122,
# MAGIC     -- IDXFR125,
# MAGIC     -- IDXFR13,
# MAGIC     -- IDXFR130,
# MAGIC     -- IDXFR131,
# MAGIC     -- IDXFR136,
# MAGIC     -- IDXFR138,
# MAGIC     -- IDXFR139,
# MAGIC     -- IDXFR14,
# MAGIC     -- IDXFR146,
# MAGIC     -- IDXFR15,
# MAGIC     -- IDXFR153,
# MAGIC     -- IDXFR16,
# MAGIC     -- IDXFR162,
# MAGIC     -- IDXFR169,
# MAGIC     -- IDXFR17,
# MAGIC     -- IDXFR172,
# MAGIC     -- IDXFR173,
# MAGIC     -- IDXFR174,
# MAGIC     -- IDXFR176,
# MAGIC     -- IDXFR18,
# MAGIC     -- IDXFR184,
# MAGIC     -- IDXFR187,
# MAGIC     -- IDXFR188,
# MAGIC     -- IDXFR19,
# MAGIC     -- IDXFR20,
# MAGIC     -- IDXFR205,
# MAGIC     -- IDXFR206,
# MAGIC     -- IDXFR207,
# MAGIC     -- IDXFR208,
# MAGIC     -- IDXFR209,
# MAGIC     -- IDXFR21,
# MAGIC     -- IDXFR210,
# MAGIC     -- IDXFR211,
# MAGIC     -- IDXFR212,
# MAGIC     -- IDXFR213,
# MAGIC     -- IDXFR214,
# MAGIC     -- IDXFR215,
# MAGIC     -- IDXFR216,
# MAGIC     -- IDXFR217,
# MAGIC     -- IDXFR218,
# MAGIC     -- IDXFR219,
# MAGIC     -- IDXFR22,
# MAGIC     -- IDXFR220,
# MAGIC     -- IDXFR221,
# MAGIC     -- IDXFR222,
# MAGIC     -- IDXFR223,
# MAGIC     -- IDXFR224,
# MAGIC     -- IDXFR225,
# MAGIC     -- IDXFR226,
# MAGIC     -- IDXFR227,
# MAGIC     -- IDXFR228,
# MAGIC     -- IDXFR229,
# MAGIC     -- IDXFR23,
# MAGIC     -- IDXFR230,
# MAGIC     -- IDXFR231,
# MAGIC     -- IDXFR232,
# MAGIC     -- IDXFR233,
# MAGIC     -- IDXFR234,
# MAGIC     -- IDXFR235,
# MAGIC     -- IDXFR236,
# MAGIC     -- IDXFR24,
# MAGIC     -- IDXFR25,
# MAGIC     -- IDXFR26,
# MAGIC     -- IDXFR27,
# MAGIC     -- IDXFR28,
# MAGIC     -- IDXFR29,
# MAGIC     -- IDXFR30,
# MAGIC     -- IDXFR31,
# MAGIC     -- IDXFR32,
# MAGIC     -- IDXFR33,
# MAGIC     -- IDXFR34,
# MAGIC     -- IDXFR35,
# MAGIC     -- IDXFR36,
# MAGIC     -- IDXFR37,
# MAGIC     -- IDXFR38,
# MAGIC     -- IDXFR39,
# MAGIC     -- IDXFR40,
# MAGIC     -- IDXFR41,
# MAGIC     -- IDXFR42,
# MAGIC     -- IDXFR43,
# MAGIC     -- IDXFR44,
# MAGIC     -- IDXFR45,
# MAGIC     -- IDXFR46,
# MAGIC     -- IDXFR47,
# MAGIC     -- IDXFR48,
# MAGIC     -- IDXFR49,
# MAGIC     -- IDXFR50,
# MAGIC     -- IDXFR51,
# MAGIC     -- IDXFR52,
# MAGIC     -- IDXFR53,
# MAGIC     -- IDXFR54,
# MAGIC     -- IDXFR55,
# MAGIC     -- IDXFR56,
# MAGIC     -- IDXFR57,
# MAGIC     -- IDXFR58,
# MAGIC     -- IDXFR59,
# MAGIC     -- IDXFR60,
# MAGIC     -- IDXFR61,
# MAGIC     -- IDXFR62,
# MAGIC     -- IDXFR63,
# MAGIC     -- IDXFR64,
# MAGIC     -- IDXFR65,
# MAGIC     -- IDXFR66,
# MAGIC     -- IDXFR67,
# MAGIC     -- IDXFR68,
# MAGIC     -- IDXFR69,
# MAGIC     -- IDXFR70,
# MAGIC     -- IDXFR71,
# MAGIC     -- IDXFR72,
# MAGIC     -- IDXFR73,
# MAGIC     -- IDXFR74,
# MAGIC     -- IDXFR75,
# MAGIC     -- IDXFR76,
# MAGIC     -- IDXFR77,
# MAGIC     -- IDXFR78,
# MAGIC     -- IDXFR79,
# MAGIC     -- IDXFR80,
# MAGIC     -- IDXFR81,
# MAGIC     -- IDXFR82,
# MAGIC     -- IDXFR83,
# MAGIC     -- IDXFR84,
# MAGIC     -- IDXFR85,
# MAGIC     -- IDXFR86,
# MAGIC     -- IDXFR87,
# MAGIC     -- IDXFR88,
# MAGIC     -- IDXFR89,
# MAGIC     -- IDXFR90,
# MAGIC     -- IDXFR91,
# MAGIC     -- IDXFR92,
# MAGIC     -- IDXFR93,
# MAGIC     -- IDXFR94,
# MAGIC     -- IDXFR95,
# MAGIC     -- IDXFR96,
# MAGIC     -- IDXFR97,
# MAGIC     -- IDXFR98,
# MAGIC     -- IDXFR99,
# MAGIC     -- IDXID01,
# MAGIC     -- IDXID03,
# MAGIC     -- IDXID04,
# MAGIC     -- IDXID05,
# MAGIC     -- IDXID06,
# MAGIC     -- IDXID07,
# MAGIC     -- IDXID09,
# MAGIC     -- IDXID10,
# MAGIC     -- IDXID11,
# MAGIC     -- IDXID12,
# MAGIC     -- IDXID13,
# MAGIC     -- IDXID14,
# MAGIC     -- IDXID15,
# MAGIC     -- IDXID17,
# MAGIC     -- IDXID18,
# MAGIC     -- IDXID19,
# MAGIC     -- IDXID20,
# MAGIC     -- IDXID21,
# MAGIC     -- IDXID23,
# MAGIC     -- IDXID24,
# MAGIC     -- IDXID25,
# MAGIC     -- IDXID26,
# MAGIC     -- IDXID27,
# MAGIC     -- IDXID28,
# MAGIC     -- IDXID30,
# MAGIC     -- IDXID32,
# MAGIC     -- IDXID33,
# MAGIC     -- IDXID34,
# MAGIC     -- IDXID35,
# MAGIC     -- IDXID36,
# MAGIC     -- IDXID37,
# MAGIC     -- IDXSF190,
# MAGIC     -- IDXSF191,
# MAGIC     -- IDXSF192,
# MAGIC     -- IDXSF193,
# MAGIC     -- IDXSF194,
# MAGIC     -- IDXSF197,
# MAGIC     -- IDXSF202,
# MAGIC     -- IDXSF237,
# MAGIC     -- IDXSF238,
# MAGIC     -- IDXSF240,
# MAGIC     -- IDXSF241,
# MAGIC     -- IDXSF244,
# MAGIC     IN04,
# MAGIC     IN60,
# MAGIC     IN84,
# MAGIC     MC60,
# MAGIC     PR09,
# MAGIC     PR10,
# MAGIC     PR100,
# MAGIC     PR11,
# MAGIC     PR116,
# MAGIC     PR117,
# MAGIC     PR119,
# MAGIC     PR120,
# MAGIC     PR123,
# MAGIC     PR124,
# MAGIC     PR14,
# MAGIC     PR15,
# MAGIC     PR21,
# MAGIC     PR22,
# MAGIC     PR30,
# MAGIC     PR41,
# MAGIC     PR42,
# MAGIC     PR43,
# MAGIC     PR44,
# MAGIC     PR45,
# MAGIC     PR46,
# MAGIC     PR47,
# MAGIC     PR50,
# MAGIC     PR51,
# MAGIC     PR52,
# MAGIC     PR68,
# MAGIC     PR69,
# MAGIC     PR70,
# MAGIC     PR73,
# MAGIC     PR74,
# MAGIC     PR75,
# MAGIC     PR95,
# MAGIC     PR97,
# MAGIC     PR98,
# MAGIC     RE01,
# MAGIC     RE02,
# MAGIC     RE03,
# MAGIC     RE04,
# MAGIC     RE05,
# MAGIC     RE06,
# MAGIC     RE07,
# MAGIC     RE09,
# MAGIC     RE28,
# MAGIC     RE29,
# MAGIC     RE33,
# MAGIC     RE336,
# MAGIC     RE34,
# MAGIC     RE35,
# MAGIC     RE37,
# MAGIC     RE38,
# MAGIC     RE41,
# MAGIC     RE42,
# MAGIC     RE43,
# MAGIC     RE60,
# MAGIC     RE61,
# MAGIC     RE62,
# MAGIC     RE75,
# MAGIC     RE76,
# MAGIC     RE77,
# MAGIC     RE81,
# MAGIC     RE82,
# MAGIC     RE83,
# MAGIC     RE84,
# MAGIC     RE91,
# MAGIC     RR02,
# MAGIC     -- RR04,
# MAGIC     RR60,
# MAGIC     RR62,
# MAGIC     RR84,
# MAGIC     RR91,
# MAGIC     SD60,
# MAGIC     SL60,
# MAGIC     monthlyHousingCostCents,
# MAGIC     housingStatus,
# MAGIC     case
# MAGIC     when personalIncomeBand = 'a.\$0 - \$20,000,' then 10000
# MAGIC     when personalIncomeBand = 'b.\$20,000 - \$40,000' then 30000
# MAGIC     when personalIncomeBand = 'c.\$40,000 - \$60,000' then 50000
# MAGIC     when personalIncomeBand = 'd.\$60,000 - \$80,000' then 70000
# MAGIC     when personalIncomeBand = 'e.\$80,000 - \$100,000' then 90000
# MAGIC     when personalIncomeBand = 'f.\$100,000 - \$120,000' then 110000
# MAGIC     when personalIncomeBand = 'g.\$120,000 - \$140,000' then 130000
# MAGIC     when personalIncomeBand = 'h.\$140,000+' then 150000
# MAGIC     else -10000 end
# MAGIC     as income,
# MAGIC     originalCreditScore,
# MAGIC     substring(userInformation.physicalAddress.postal, 1, 3) as FSA,
# MAGIC     isdefault_1y
# MAGIC   from
# MAGIC     neo_views_credit_risk.wk_feature_and_target_no_hc as a
# MAGIC     left join (
# MAGIC       select
# MAGIC         distinct userId,
# MAGIC         personalIncomeBand,
# MAGIC         originalCreditScore
# MAGIC       from
# MAGIC         neo_trusted_analytics.earl_account
# MAGIC     ) as b on a.userId = b.userId
# MAGIC   where
# MAGIC     brand = 'NEO'
# MAGIC     and decision = 'APPROVED'
# MAGIC     and type = 'STANDARD') as base
# MAGIC left join dbt_dev_alex_karklins.census_income as ci on base.fsa = ci.fsa

# COMMAND ----------

from pyspark.sql.functions import *

modeling = _sqldf
amount_missing_df = modeling.select([(count(when(col(c).isNull(), c))/count(lit(1))).alias(c) for c in modeling.columns])

# COMMAND ----------

display(amount_missing_df)

# COMMAND ----------

#all idx and RR04 creditScore producttypename credit facility
